# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frame.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\x07\x61ick.ai\"v\n\x0c\x46rameRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x14\n\x0c\x65\x64ge_node_id\x18\x02 \x01(\t\x12\x12\n\nframe_data\x18\x03 \x01(\x0c\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x16\n\x0e\x61nalysis_types\x18\x05 \x03(\t\"\xc5\x01\n\x0e\x41nalysisResult\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12,\n\tpassenger\x18\n \x01(\x0b\x32\x17.aick.ai.PassengerStatsH\x00\x12*\n\x08\x62\x65havior\x18\x0b \x01(\x0b\x32\x16.aick.ai.BehaviorEventH\x00\x12)\n\x07vehicle\x18\x0c \x01(\x0b\x32\x16.aick.ai.VehicleRecordH\x00\x42\x08\n\x06result\"w\n\x0ePassengerStats\x12\x13\n\x0b\x65nter_count\x18\x01 \x01(\x05\x12\x12\n\nexit_count\x18\x02 \x01(\x05\x12\x14\n\x0cinside_count\x18\x03 \x01(\x05\x12&\n\nzone_stats\x18\x04 \x03(\x0b\x32\x12.aick.ai.ZoneStats\"4\n\tZoneStats\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x14\n\x0cperson_count\x18\x02 \x01(\x05\"\xa5\x01\n\rBehaviorEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x12\n\nposition_x\x18\x03 \x01(\x02\x12\x12\n\nposition_y\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\x12\x15\n\rsnapshot_path\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\"e\n\rVehicleRecord\x12\x14\n\x0cplate_number\x18\x01 \x01(\t\x12\x13\n\x0bplate_color\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x15\n\rsnapshot_path\x18\x04 \x01(\t2S\n\rFrameAnalysis\x12\x42\n\x0c\x41nalyzeFrame\x12\x15.aick.ai.FrameRequest\x1a\x17.aick.ai.AnalysisResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=24
  _globals['_FRAMEREQUEST']._serialized_end=142
  _globals['_ANALYSISRESULT']._serialized_start=145
  _globals['_ANALYSISRESULT']._serialized_end=342
  _globals['_PASSENGERSTATS']._serialized_start=344
  _globals['_PASSENGERSTATS']._serialized_end=463
  _globals['_ZONESTATS']._serialized_start=465
  _globals['_ZONESTATS']._serialized_end=517
  _globals['_BEHAVIOREVENT']._serialized_start=520
  _globals['_BEHAVIOREVENT']._serialized_end=685
  _globals['_VEHICLERECORD']._serialized_start=687
  _globals['_VEHICLERECORD']._serialized_end=788
  _globals['_FRAMEANALYSIS']._serialized_start=790
  _globals['_FRAMEANALYSIS']._serialized_end=873
# @@protoc_insertion_point(module_scope)
